library(testthat)

# IMPORTANT
# the URL to paste in the browser to compare against the R scripts, when using ALL,
# must have been generated by cat(my_url), which will remove the backslahes.
# otherwise, the paper results will be those of the ANY.

context("match url with and without backslashes")
test_that("papers by type match for ALL", {
    url_nn <- make_search_url(query = "neural network",
                              how = "all"
    )

    expect_true(url_nn == 'https://www.onepetro.org/search?q=\"neural+network\"&peer_reviewed=&published_between=&from_year=&to_year=')
    expect_true(url_nn == 'https://www.onepetro.org/search?q="neural+network"&peer_reviewed=&published_between=&from_year=&to_year=')
    expect_true(capture.output(cat(url_nn)) == 'https://www.onepetro.org/search?q="neural+network"&peer_reviewed=&published_between=&from_year=&to_year=')

    paper_count <- get_papers_count(url_nn)
    expect_equal(paper_count, 3237)
})
