---
title: "Production Engineering and ML"
output:
  html_document:
    df_print: paged
---

```{r setup, include=F, error=T, message=F, warning=F}
knitr::opts_chunk$set(echo = TRUE, 
                      comment = NA, 
                      error = TRUE, 
                      warning = FALSE, 
                      message = FALSE, 
                      fig.align = 'center')
```

# Retrieve papers from OnePetro

## well +production + production engineering + machine learning

```{r}
library(petro.One)
library(dplyr)

# provide two different set of keywords to combine as vectors
major   <- c("production", "production engineering")
minor   <- c("machine-learning", "machine learning")


paper_results <- run_papers_search(major, minor, get_papers = TRUE, 
                                   verbose = FALSE, len_keywords = 4)
```


```{r}
(papers <- paper_results$papers)
```


```{r echo=FALSE}
# No need

# # eliminate duplicates by paper_id and paper title
# papers <- papers %>% 
#     distinct(paper_id, book_title, .keep_all = TRUE) %>% 
#     print
```


### what papers have machine learning in the title
```{r}
papers %>%
    # machine learning OR machine-learning
    filter(grepl(pattern = "machine[-\\s]learning", 
                 x = book_title, ignore.case = TRUE, perl = TRUE))
```

### what papers have artificial intelligence in the title
```{r}
papers %>%
    # machine learning OR machine-learning
    filter(grepl(pattern = "artificial[-\\s]intelligence", 
                 x = book_title, ignore.case = TRUE, perl = TRUE))
```
