---
title: "R Notebook"
output: html_notebook
---

```{r}
#' @param len_keywords length of the keywords to form the filename of the rda file
run_papers_search <- function(..., 
                                get_papers = TRUE, 
                                sleep = 3, 
                                verbose = TRUE,
                                len_keywords = 3) {
    
    # join the keywords to searh in OnePetro
    papers_obj <- join_keywords(..., get_papers = get_papers, 
                                sleep = sleep, verbose = verbose)
    keywords <- papers_obj$keywords
    papers   <- papers_obj$papers
    
    # create an object to group all search objects, including paper results
    search_keywords <- list(...)
    
    
    # create filename from the keywords
    comb_keyw <- c(search_keywords[1], search_keywords[2])    # combine keywords
    rda_filename <- paste0(lapply(list(unlist(comb_keyw)), 
                       function(x) paste(substr(x, 1, len_keywords), collapse = "_")),
                       ".rda")
    
    paper_search_obj <- rNodal.utils:::as_named_list(papers, keywords, 
                                                     search_keywords, rda_filename)
    
    # save the object to RDA file
    save(paper_search_obj, file = rda_filename)
    return(paper_search_obj)
}

```


# Retrieve papers from OnePetro

## well +production + production engineering + machine learning

```{r}
library(petro.One)
library(dplyr)

# provide two different set of keywords to combine as vectors
major   <- c("well", "production", "production engineering")
minor   <- c("machine-learning", "machine learning")

papers_obj <- join_keywords(major, minor, get_papers = TRUE, sleep = 3, verbose = TRUE)

# save findings. save the three objects as one
well_prod_eng_ml_obj <- rNodal.utils:::as_named_list(major, minor, papers_obj)
save(well_prod_eng_ml_obj, file = paste0("well_prod_eng_ml_obj", ".rda"))

# load previous findings
load(file = paste0("well_prod_eng_ml_obj", ".rda"))
papers <- well_prod_eng_ml_obj$papers_obj$papers
papers
```






```{r}
major   <- c("well", "production", "production engineering")
minor   <- c("machine-learning", "machine learning")

search_result <- run_papers_search(major, minor, verbose = FALSE, len_keywords = 4)
```


## production + production engineering + machine learning

```{r}
library(petro.One)
library(dplyr)

# provide two different set of keywords to combine as vectors
major   <- c("production", "production engineering")
minor   <- c("machine-learning", "machine learning")

papers_obj <- join_keywords(major, minor, get_papers = TRUE, sleep = 3, verbose = TRUE)

# save findings. save the three objects as one
prod_eng_ml_obj <- rNodal.utils:::as_named_list(major, minor, papers_obj)
save(prod_eng_ml_obj, file = paste0("prod_eng_ml.obj", ".rda"))

# load previous findings
load(file = paste0("prod_eng_ml_obj", ".rda"))
papers <- prod_eng_ml.obj$papers_obj$papers
papers
```


