---
title: "R Notebook"
output: html_notebook
---

```{r}
library(petro.One)

my_url <- make_search_url(query = "deepwater", 
                          dc_type = "conference-paper"
                          )

webpage <- xml2::read_html(my_url)

author1_data_html <- html_nodes(webpage, '.result-item-author:nth-child(1)')
author1_data_txt <- html_text(author1_data_html)
author1_data <- trimws(gsub("\n", "", author1_data_txt))
author1_data
```

```{r}
author2_data_html <- html_nodes(webpage, '.result-item-author:nth-child(2)')
author2_data_txt <- html_text(author2_data_html)
author2_data <- trimws(gsub("\n", "", author2_data_txt))
author2_data
```

```{r}
author3_data_html <- html_nodes(webpage, '.result-item-author:nth-child(3)')
author3_data_txt <- html_text(author3_data_html)
author3_data <- trimws(gsub("\n", "", author3_data_txt))
author3_data
```

```{r}
library(petro.One)

my_url <- make_search_url(query = "deepwater", 
                          dc_type = "conference-paper"
                          )

webpage <- xml2::read_html(my_url)

authors_data_html <- html_nodes(webpage, '.result-item-authors')
authors_data_txt <- html_text(authors_data_html)
authors_data <- trimws(gsub("\n", "", authors_data_txt))
authors_data
```

